CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  dt_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS birthdates (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL DEFAULT 1,
  peoplename VARCHAR(255) NOT NULL,
  birthdate VARCHAR(10) NOT NULL,
  dt_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  dt_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS birthdates_tags (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tag VARCHAR(255) NOT NULL,
  people_id INT NOT NULL
);
